# Generated by Django 2.2.4 on 2019-08-09 07:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense_info',
            new_name='ExpenseInfo',
        ),
    ]
