# Generated by Django 2.2.4 on 2019-08-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190809_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categories_id',
            new_name='categories',
        ),
    ]
