# Generated by Django 2.2.4 on 2019-08-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190809_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseinfo',
            old_name='expense_id',
            new_name='expense',
        ),
        migrations.RenameField(
            model_name='expenseinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
