# Generated by Django 2.2.4 on 2019-08-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190809_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='members',
        ),
    ]
